server:
  port: 8080
  context-path: /


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 011762
  mvc:
    view:
      prefix: /
      suffix: .html

